### ISSUE TITLE
Replace flannel with cilium

### ISSUE THREAD

**Issue by abelfodil** [arch-anes/self-hosted-services#24]
https://docs.projectcalico.org/getting-started/kubernetes/k3s/quickstart

**Comment by abelfodil** [comment]
https://www.youtube.com/results?search_query=calico+vs+flannel

**Comment by abelfodil** [comment]
https://github.com/k3s-io/k3s/issues/535

**Comment by abelfodil** [comment]
https://rancher.com/docs/k3s/latest/en/advanced/#enabling-legacy-iptables-on-raspbian-buster

**Comment by abelfodil** [comment]
https://github.com/k3s-io/k3s-ansible/blob/master/roles/raspberrypi/tasks/prereq/Raspbian.yml

**Comment by abelfodil** [comment]
Another possibility is Cilium https://docs.cilium.io/en/stable/operations/system_requirements/

**Comment by abelfodil** [comment]
Calico requirements: https://docs.tigera.io/calico/latest/getting-started/kubernetes/requirements

**Comment by abelfodil** [comment]
Closing as it's too complex and not needed at the moment. Maybe will reopen in the future.

**Comment by abelfodil** [comment]
Calico would be required if https://kubernetes.io/docs/concepts/services-networking/network-policies/ were to be used.

Example use-case: routing a pod's entire traffic through another pod.

**Comment by abelfodil** [comment]
Example use case:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: force-traffic-through-vpn
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: transmission
  policyTypes:
    - Egress
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: vpn
      ports:
        - protocol: TCP
          port: 51820
```
