### ISSUE TITLE
Ditch Duplicati for a more reliable backup solutions

### ISSUE THREAD

**Issue by abelfodil** [arch-anes/self-hosted-services#80]
https://old.reddit.com/r/selfhosted/comments/101lgga/duplicati_has_crossed_me_for_the_last_time/

https://github.com/restic/restic

https://forum.duplicati.com/t/why-the-negative-reviews/19693

https://blog.gurucomputing.com.au/Offsite%20Docker%20Backups%20with%20Kopia/Offsite%20Docker%20Backups%20with%20Kopia/

https://www.urbackup.org/features.html

https://kopia.io/docs/features/

https://github.com/gilbertchen/duplicacy

**Comment by abelfodil** [comment]
https://autorestic.vercel.app/

**Comment by abelfodil** [comment]
https://itnext.io/simple-backups-for-small-kubernetes-clusters-1203c835fd97

**Comment by abelfodil** [comment]
I would love to use restic, but the current obstacles are:
1. It's a CLI with one-shot backup. There's no scheduling out of the box.
2. Solutions that wrap it for Kubernetes are velero and k8up. 
   - k8sup backs up PVCs only and not `hostPath`s, there for I won't consider it.
   - Velero seems more flexible but again the `hostPath` is not supported ([ref](https://velero.io/docs/v1.15/file-system-backup/#limitations)) and the documentation around CRDs is lacking.
 3. Ideally I'd create a k8s CronJob that execute restic, but I'd also like to run it on multiple hosts, but there's no DaemonSet like behavior for CronJob. There are workarounds though: https://stackoverflow.com/a/72286391

I could go with Solution 3, but at this point I'm not seeing the value. Duplicati is stabilizing, and I think I'll stay with it until better solutions come around or the situation around PVC/hostPath changes.

**Comment by abelfodil** [comment]
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: restic-backup
spec:
  selector:
    matchLabels:
      app: restic
  template:
    metadata:
      labels:
        app: restic
    spec:
      containers:
      - name: restic
        image: restic/restic:latest
        envFrom:
        - secretRef:
            name: restic-secrets
        volumeMounts:
        - name: host-data
          mountPath: /data
          readOnly: true
        - name: excludes-file
          mountPath: /config/excludes.txt
          subPath: excludes.txt
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            # Run Restic backup
            restic -r b2:<b2-bucket-name>:<b2-path> \
              backup /data \
              --exclude-file /config/excludes.txt \
              --host $(hostname) \
              || curl -X POST -H "Content-Type: application/json" \
              -d '{"text": "Restic backup failed on host $(hostname)."}' \
              <your-webhook-url>
            
            # Wait until midnight
            sleep $(( $(date -d "tomorrow 00:00" +%s) - $(date +%s) ))
          done
        volumeMounts:
        - name: host-data
          hostPath:
            path: /path/to/data
        - name: excludes-file
          configMap:
            name: restic-excludes
        restartPolicy: Always

---
apiVersion: v1
kind: Secret
metadata:
  name: restic-secrets
type: Opaque
data:
  B2_ACCOUNT_ID: <base64-encoded-account-id>
  B2_ACCOUNT_KEY: <base64-encoded-application-key>
  RESTIC_PASSWORD: <base64-encoded-restic-password>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restic-excludes
data:
  excludes.txt: |
    /data/folder-to-exclude
    /data/temp-files
```

**Comment by abelfodil** [comment]
```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: restic-backup-job
spec:
  schedule: "0 0 * * *" # Run daily at midnight
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restic-backup
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              echo "Creating DaemonSet for Restic backup..."
              kubectl apply -f /config/restic-daemonset.yaml
              echo "Waiting for backup completion..."
              # Wait until backup completion or timeout
              while kubectl get pods -l app=restic-backup | grep -q Running; do
                sleep 30
              done
              echo "Deleting DaemonSet after completion..."
              kubectl delete daemonset restic-backup
            volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
          volumes:
          - name: config-volume
            configMap:
              name: restic-config
          restartPolicy: OnFailure

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: restic-backup
  labels:
    app: restic-backup
spec:
  selector:
    matchLabels:
      app: restic-backup
  template:
    metadata:
      labels:
        app: restic-backup
    spec:
      containers:
      - name: restic
        image: restic/restic:latest
        envFrom:
        - secretRef:
            name: restic-secrets
        volumeMounts:
        - name: host-data
          mountPath: /data
          readOnly: true
        - name: excludes-file
          mountPath: /config/excludes.txt
          subPath: excludes.txt
        command:
        - /bin/sh
        - -c
        - |
          restic -r b2:<b2-bucket-name>:<b2-path> \
            backup /data \
            --exclude-file /config/excludes.txt \
            --host $(hostname)
      volumes:
      - name: host-data
        hostPath:
          path: /path/to/data
      - name: excludes-file
        configMap:
          name: restic-excludes
      restartPolicy: OnFailure

---
apiVersion: v1
kind: Secret
metadata:
  name: restic-secrets
type: Opaque
data:
  B2_ACCOUNT_ID: <base64-encoded-account-id>
  B2_ACCOUNT_KEY: <base64-encoded-application-key>
  RESTIC_PASSWORD: <base64-encoded-restic-password>

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restic-excludes
data:
  excludes.txt: |
    /data/temp
    /data/cache

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: restic-config
data:
  restic-daemonset.yaml: |
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: restic-backup
      labels:
        app: restic-backup
    spec:
      selector:
        matchLabels:
          app: restic-backup
      template:
        metadata:
          labels:
            app: restic-backup
        spec:
          containers:
          - name: restic
            image: restic/restic:latest
            envFrom:
            - secretRef:
                name: restic-secrets
            volumeMounts:
            - name: host-data
              mountPath: /data
              readOnly: true
            - name: excludes-file
              mountPath: /config/excludes.txt
              subPath: excludes.txt
            command:
            - /bin/sh
            - -c
            - |
              restic -r b2:<b2-bucket-name>:<b2-path> \
                backup /data \
                --exclude-file /config/excludes.txt \
                --host $(hostname)
          volumes:
          - name: host-data
            hostPath:
              path: /path/to/data
          - name: excludes-file
            configMap:
              name: restic-excludes
          restartPolicy: OnFailure

```
